### ISSUE TITLE
compilation failed for package ‘mirtCAT’

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/mirtCAT#1]
Dear Phil,

![2015-01-26 05 00 33](https://cloud.githubusercontent.com/assets/8172694/5893003/69e3b4be-a518-11e4-8c42-9bb871817349.png)

![2015-01-26 05 02 34](https://cloud.githubusercontent.com/assets/8172694/5893012/8fac985a-a518-11e4-9c34-841929c3df34.png)

I encountered that messages. So I attached messages with my session information. Cheers.
## 

Seongho Bae

**Comment by philchalmers** [comment]
Thanks Seongho, a patch was just sent to CRAN today to fix this (has to do with the latest RcppArmadillo package update). Version 0.4.2 fixes this issue.

**Comment by philchalmers** [comment]
You could just install the dev version. There already has been two bugs fixes pushed from the latest stable build, so I would probably recommend that route.

**Comment by seonghobae** [comment]
Okay, Cool! It works!
