### ISSUE TITLE
Random freezes when loading mirtCAT

### ISSUE THREAD

**Issue by whiteplastic** [philchalmers/mirtCAT#10]
Sometimes, I'm experiencing freezes when loading the library. I have `library("mirtCAT")` at the beginning of my script, so this library is loaded every time I run the script. This works mostly fine, but every now and then, R freezes at this point, so  that I have to interrupt R manually.

Have you ever experienced this or do you have a hypothesis on why this might occur?

**Comment by philchalmers** [comment]
That's troubling to hear, but no I've never witnessed this happen. I've tested this mostly on different versions of Ubuntu though, so maybe it's related to using shiny on your operating system?

**Comment by whiteplastic** [comment]
I'm using Mac OS X for testing, so maybe it's different on another system.

**Comment by philchalmers** [comment]
I can try to reproduce it on my end in case it's something cross-platform (you don't have to post your scripts here, a private email is fine). I'll try it on Windows as well to see if it comes up there too.

**Comment by philchalmers** [comment]
This may have been related to R's lazy evaluation. I've forced the evaluation to be made immediately, which appears to remove some random issues that have come up on my end as well. Let me know if the newer version is more stable for you.

**Comment by whiteplastic** [comment]
Ok, I'll let you now. Thank you.
