### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by whiteplastic** [philchalmers/mirtCAT#11]
Is there an easy way to make mirtCAT use an encrypted connection? I would have to do complicated reverse-proxying action with another http server, which gets really annoying when assessing 30 people in parallel.

**Comment by philchalmers** [comment]
I think SSL is a server-based issue, doesn't really have much to do with `mirtCAT`. http://tagteam.harvard.edu/hub_feeds/1981/feed_items/2142545

**Comment by whiteplastic** [comment]
Ok. After reverse-proxying mirtCAT, the assessment isn't working anymore. I get to the first page but after clicking "continue", the assessment won't start.
I successfully ran other shiny apps after reverse-proxying. Is there anything I have to adjust manually in mirtCAT? 

I tried explicitly proxying the /shared/-folder as well, but it seems to include all javascript files just fine. 
This seems to be a websocket issue, I have to tunnel the websocket connection as well. Sorry to bother you.
