### ISSUE TITLE
Error : object '.MCE' not found

### ISSUE THREAD

**Issue by Abuamany** [philchalmers/mirtCAT#13]
Pls advice: 
Listening on http://127.0.0.1:7780
Warning: Error in tagList: object '.MCE' not found
Stack trace (innermost first):
    43: tagList
    42: attachDependencies
    41: bootstrapPage
    40: fluidPage
    39: ui [/home/peopleanalytics/Desktop/mirtCAT-master/R/ui.R#3]
     1: runApp
Error : object '.MCE' not found

**Comment by philchalmers** [comment]
1) have you tested this with the development version of `mirt` and `mirtCAT`? and 2) if this is still an issue after updating, please provide a simple reproducible example.
