### ISSUE TITLE
Typo in command on docs.

### ISSUE THREAD

**Issue by ramiroluz** [philchalmers/mirtCAT#16]
I believe there is a typo in a server command.

Under **some useful commands**, last item:

- sudo systemctl restart shiny-server
- status shiny-server

Believe it should be:

- sudo systemctl restart shiny-server
- sudo systemctl status shiny-server

http://philchalmers.github.io/mirtCAT/server-setup.html

**Comment by philchalmers** [comment]
Is this new in the `shiny` documentation? Checking the status of the `shiny-server` didn't previously require super user access. Please confirm.

**Comment by ramiroluz** [comment]
I believe that it need at least the command:

`# systemctl status shiny-server`

status by itself is not a command.

**Comment by philchalmers** [comment]
Perhaps not, but the command listed is `status shiny-server`, without the `systemctl` part. That is listed in the documentation as valid: http://docs.rstudio.com/shiny-server/

**Comment by philchalmers** [comment]
I see it now. This command was only valid for Ubuntu servers up to version 14.10. For later version this does not work. I'll correct this in my docs; thanks.
