### ISSUE TITLE
ML method with insufficient variability

### ISSUE THREAD

**Issue by telupild** [philchalmers/mirtCAT#17]
Hi,
using following R code

```
set.seed(1221)

### loading data
library("ShinyItemAnalysis") 
data(dataMedical)
dataM=dataMedical[,1:100]

### fitting IRT model
library("mirt") 
mod1<-mirt(dataM,1,itemtype = "3PL")

### generating responses
library("mirtCAT")
N<-100
Theta<-matrix(rnorm(N))
responses<-generate_pattern(mod1,Theta=Theta)


### fitting CAT

modMIML<-mirtCAT(mo=mod1,local_pattern = responses,start_item = "MI",
                 method="ML",criteria="MI")
```

I get following error:

> Error in solve.default(estimate$hessian[pick, pick, drop = FALSE]) : 
>   'a' is 0-diml
> Error in sqrt(diag(vcov)) : non-numeric argument to mathematical function
> Error in if (.Object@stage > 1L && !any(is.nan(diff)) && all(.Object@met_SEM)) .Object@stop_now <- TRUE : 
>   missing value where TRUE/FALSE needed
> 

I assume that it happens due to insufficient variability of some response patterns for maximum likelihood method but from the documentation for mirtCAT() function I would expect using of "MAP" for these respond patterns (fitting CAT for "MAP" works well). 

Am I overlooking or misunderstanding something?
Sorry to bother you.
D. T.

**Comment by philchalmers** [comment]
This likely is a bug related to ML estimation, though I'm unsure why it isn't being caught correctly. I'll take a look at it.

**Comment by philchalmers** [comment]
Should be patched now, thanks for the report.

**Comment by nittayapa** [comment]
I also got following error

> Error in if (.Object@stage > 1L && !any(is.nan(diff)) && all(.Object@met_SEM)) .Object@stop_now <- TRUE : 
  missing value where TRUE/FALSE needed

I tried to use all method ("MAP" "ML" "EAP"), but it is not work.
