### ISSUE TITLE
Include parameters via URL

### ISSUE THREAD

**Issue by dansom** [philchalmers/mirtCAT#24]
Dear Phil,

as discussed in the google group, it would be great if mirtCAT would be able to handle parameters passed to mirtCAT via the URL. An example would be

http://www.link-to-mirtcat.com?ID=XYZ

where XYZ could for example be the participant ID or any other string.

Based on [this post](https://community.rstudio.com/t/can-i-pass-parameters-to-a-shiny-app-via-url/20545/2), an edit similar to this one 
`output$parameters <- parseQueryString(session$clientData$url_search) `
 in the server-part of the app should be enough.

Thanks in advance

Daniel

**Comment by philchalmers** [comment]
Thanks. Would it be enough to simply collect this information and return it in the saved `mirtCAT()` objects somewhere? This would also allow access via the `lastpage()` function in case a table of results or something like that should be combined given the current url_search information.

**Comment by philchalmers** [comment]
Also, this principle would seem to apply to a lot of the client data information. Perhaps additional slots should be stored on a per session basis as well.

**Comment by dansom** [comment]
For my purposes that would be wonderful and absolutely sufficient :-)
