### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by AmulPatil** [philchalmers/mirtCAT#27]
Newbie to R:Sorry if issue is not formatted in right format,
facing issue while installing mirtcat package in local PC,any easy way to fix the issue.

R studio Version 1.3.1073
----------------------
R version:
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.2                         
year           2020                        
month          06                          
day            22                          
svn rev        78730                       
language       R                           
version.string R version 4.0.2 (2020-06-22)
nickname       Taking Off Again   
--------------------------

logs----
> install_github('philchalmers/mirtCAT')
Downloading GitHub repo philchalmers/mirtCAT@HEAD
√  checking for file 'C:\Users\Demons\AppData\Local\Temp\RtmpAVFLDI\remotes1d606aca2409\philchalmers-mirtCAT-9d15576/DESCRIPTION' (1.3s)
-  preparing 'mirtCAT': (1.9s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  installing the package to process help pages (770ms)
         -----------------------------------
-  installing *source* package 'mirtCAT' ...
   ** using staged installation
   ** libs
   "c:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Users/Demons/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/Demons/Documents/R/win-library/4.0/RcppArmadillo/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c CAT_functions.cpp -o CAT_functions.o
   sh: c:/rtools40/mingw64/bin/g++: No such file or directory
   make: *** [C:/PROGRA~1/R/R-40~1.2/etc/x64/Makeconf:229: CAT_functions.o] Error 127
   ERROR: compilation failed for package 'mirtCAT'
-  removing 'C:/Users/Demons/AppData/Local/Temp/RtmpOOwgbx/Rinst6b029235f/mirtCAT'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'mirtCAT' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> * installing *source* package 'mirtCAT' ...
E> ** using staged installation
E> ** libs
E> "c:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Users/Demons/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/Demons/Documents/R/win-library/4.0/RcppArmadillo/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c CAT_functions.cpp -o CAT_functions.o
E> sh: c:/rtools40/mingw64/bin/g++: No such file or directory
E> make: *** [C:/PROGRA~1/R/R-40~1.2/etc/x64/Makeconf:229: CAT_functions.o] Error 127
E> ERROR: compilation failed for package 'mirtCAT'
E> * removing 'C:/Users/Demons/AppData/Local/Temp/RtmpOOwgbx/Rinst6b029235f/mirtCAT'
E>       -----------------------------------
E> ERROR: package installation failed

**Comment by philchalmers** [comment]
This looks like you're missing the Rtools suit (`g++` cannot be located), or at the very least that the binary files have not been added to your Windows path.

**Comment by philchalmers** [comment]
This doesn't look like a specific problem with `mirtCAT`, so I'm closing this issue for now. If the issue persists after installing RTools feel free to re-open.
