### ISSUE TITLE
Bugs in the mirtCAT function

### ISSUE THREAD

**Issue by irshad001** [philchalmers/mirtCAT#3]
Hello Phil,

I have discussed this issue in brief on google group. I dug further for more criteria and I found there are many other criteria combination which are problematic and possible bugs, so I took the liberty of posting the issue here.

Here are the different combinations:

data(LSAT7)

dat=expand.table(LSAT7)

mod <- mirt(dat,1)

1) start_item = "MLWI"     criteria = 'MI', "MLWI",  'MEI', 'MEPV' and 'MPWI'

CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MLWI', criteria = 'MI',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
Error in rowSums(ll[, tmp]) : 
  'x' must be an array of at least two dimensions

> CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MLWI', criteria = 'MLWI',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
> Error in rowSums(ll[, tmp]) : 
>   'x' must be an array of at least two dimensions
> 
> CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MLWI', criteria = 'MEI',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
> Error in rowSums(ll[, tmp]) : 
>   'x' must be an array of at least two dimensions
> 
> CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MLWI', criteria = 'MEPV',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
> Error in rowSums(ll[, tmp]) : 
>   'x' must be an array of at least two dimensions
> 
> CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MLWI', criteria = 'MPWI',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
> Error in rowSums(ll[, tmp]) : 
>   'x' must be an array of at least two dimensions

2) start_item = "MEPV"     criteria = 'MI', "MLWI",  'MEI', 'MEPV' and 'MPWI'

CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MEPV', criteria = 'MI',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
Error in is(object, "DiscreteClass") : 
  trying to get slot "mo" from an object of a basic class ("NULL") with no slots

> CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MEPV', criteria = 'MLWI',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
> Error in is(object, "DiscreteClass") : 
>   trying to get slot "mo" from an object of a basic class ("NULL") with no slots
> 
> CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MEPV', criteria = 'MEPV',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
> Error in is(object, "DiscreteClass") : 
>   trying to get slot "mo" from an object of a basic class ("NULL") with no slots
> 
> CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MEPV', criteria = 'MEI',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
> Error in is(object, "DiscreteClass") : 
>   trying to get slot "mo" from an object of a basic class ("NULL") with no slots
> 
> CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MEPV', criteria = 'MPWI',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
> Error in is(object, "DiscreteClass") : 
> trying to get slot "mo" from an object of a basic class ("NULL") with no slots

3) start_item = "MPWI"     criteria = 'MI', "MLWI",  'MEI', 'MEPV' and 'MPWI'

 CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MPWI', criteria = 'MI',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
Error in rowSums(ll[, tmp]) : 
  'x' must be an array of at least two dimensions

> CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MPWI', criteria = 'MLWI',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
> Error in rowSums(ll[, tmp]) : 
>   'x' must be an array of at least two dimensions
> 
> CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MPWI', criteria = 'MEI',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
> Error in rowSums(ll[, tmp]) : 
>   'x' must be an array of at least two dimensions
> 
> CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MPWI', criteria = 'MEPV',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
> Error in rowSums(ll[, tmp]) : 
>   'x' must be an array of at least two dimensions
> 
> CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MPWI', criteria = 'MPWI',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
> Error in rowSums(ll[, tmp]) : 
>   'x' must be an array of at least two dimensions

4) start_item = "MEI"     criteria =  'MEPV' 

CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MEI', criteria = 'MEPV',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)

> findNextItem(CATdesign)
> [1] 2
> CATdesign <- updateDesign(CATdesign, items = c(2), responses = c(1), Theta = 0)
> findNextItem(CATdesign)
> Error in is(object, "DiscreteClass") : 
>   trying to get slot "mo" from an object of a basic class ("NULL") with no slots

5) start_item = "MI"     criteria =  'MEPV' 

> CATdesign <- mirtCAT(df=NULL, mod,start_item = 'MI', criteria = 'MEPV',method = "ML" ,design_elements = TRUE, local_pattern = c(1,1,1,1,1), Theta=0)
> findNextItem(CATdesign)
> [1] 3
> CATdesign <- updateDesign(CATdesign, items = c(3), responses = c(1), Theta = 0)
> findNextItem(CATdesign)
> Error in is(object, "DiscreteClass") : 
>   trying to get slot "mo" from an object of a basic class ("NULL") with no slots

**Comment by philchalmers** [comment]
Thanks, Irshad. Should be fixed now, feel free to check your code with the new version and close the issue if it works (otherwise, just keep commenting). Cheers.

**Comment by philchalmers** [comment]
Also, the `Theta` argument does not exist in this context (you probably want `thetas.start`, which goes into the `design` list rather than passed directly through `mirtCAT()`). This unmatched argument could be caught by functions like `mirt::fscores(...)` and have weird consequences, so be careful about how each function accepts its arguments.

**Comment by irshad001** [comment]
Thank you, Phil. I will keep that in mind. So the changes done to remove
this bug will be in mirtCAT 0.4.9?

On Wed, Apr 29, 2015 at 8:16 PM, Phil Chalmers notifications@github.com
wrote:

> Also, the Theta argument does not exist in this context (you probably
> want thetas.start, which goes into the design list rather than passed
> directly through mirtCAT()). This unmatched argument could be caught by
> functions like mirt::fscores(...) and have weird consequences, so be
> careful about how each function accepts its arguments.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/philchalmers/mirtCAT/issues/3#issuecomment-97453657.

## 

Regards,
Irshad Mujawar
IIT Bombay
+918879426340

**Comment by philchalmers** [comment]
Correct.
