### ISSUE TITLE
Item timer freezes after 1 minute

### ISSUE THREAD

**Issue by MagnusNordmo** [philchalmers/mirtCAT#30]
The item timer timer freezes after one minute. This happens because of as.numerics (POSIX) default behaviour is to count output minutes after one minute has passed, instead of seconds, which is required in the delta_time function. 

E.g.

`as.numeric(Sys.time() - (Sys.time() - 50))`
and
`as.numeric(Sys.time() - (Sys.time() - 62))`

**Comment by philchalmers** [comment]
Interesting, I was not aware of this behaviour. Great catch! I'll inspect your pull request and close this issue as it seems to have been fixed there.
