### ISSUE TITLE
local_pattern doesn't work when df supplied

### ISSUE THREAD

**Issue by pikrol** [philchalmers/mirtCAT#35]
Hi, 

When I try to supply to mirtCAT function both df and local_pattern I have the following message:

> Error in command 'person$responses[pick] <- which(test@item_options[[pick]] %in% ':
  change has length 0

I can't find any discrepancy between my df and pattern. I try adjusting types of both. I give pattern as numeric matrix etc.  nothing works

![error](https://user-images.githubusercontent.com/44268776/101156389-d11f1900-3628-11eb-96d9-48461f4cde31.png)

**Comment by philchalmers** [comment]
Can you provide a reprex of this behaviour? It's possible that you've defined different classes in you df object and response pattern inputs such that they do not match, and therefore the %in% operation returns missing/null values.

**Comment by pikrol** [comment]
``` r
library(mirtCAT)
#> Warning: package 'mirtCAT' was built under R version 3.6.3
#> Loading required package: mirt
#> Warning: package 'mirt' was built under R version 3.6.3
#> Loading required package: stats4
#> Loading required package: lattice
#> Loading required package: shiny
options(stringsAsFactors =  FALSE)

a1 <- c(0,0.5,1)
d <- c(0,0.5,1)
pars <- data.frame(a1=a1, d=d)
mirt_object <- generate.mirt_object(pars, '2PL')

questions <- c("aba", "baa", "aab")
answers <- rep(1, 3)
choices <- data.frame(A = (rep(0, 3)), B = (rep(1, 3)))
df <- data.frame(Questions=questions, Answer=answers, Option=choices, Type = 'none')

responses <- data.frame(aba = 1, baa = 0, aab = 1)

mirtCAT_results <- mirtCAT(df = df, mo = mirt_object, local_pattern = responses)
#> Error in person$responses[pick] <- which(test@item_options[[pick]] %in% : replacement has length zero
```

<sup>Created on 2020-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by philchalmers** [comment]
Thanks. The issue related to `Type = 'none'`, as in the GUI responses when the none type is selected there is no responses provided by definition. However, if this to be run offline then I don't see the issue with leaving the none type as supported despite its ambiguity. Please install the lastest dev for the fix.
