### ISSUE TITLE
Pass multiple items and responses to updateDesign

### ISSUE THREAD

**Issue by NDStrahilevitz** [philchalmers/mirtCAT#37]
Hello!

In the documentation there exists an example where multiple items and responses are passed to a Desgin object as such(Pg. 12):
```
# determine next item if item 1 and item 10 were answered correctly, and Theta = 0.5
CATdesign <- updateDesign(CATdesign, items = c(1, 10), responses = c(1, 1), Theta = 0.5)
findNextItem(CATdesign)
findNextItem(CATdesign, all_index = TRUE) # all items rank in terms of most optimal
```

Sadly this does not seem to work, and the later documentation seems to not even include these parameters, instead only allowing a single item and response pair being passed (this can be confirmed by the code itself).

This feature would be really useful for me personally, so I am curious if this was ever intended behavior and if it is planned to ever support it (possibly again?).

Thanks!

**Comment by philchalmers** [comment]
Thanks for the issue. The example code in the documentation was definitely out of date. I've updated the example to reflect what was previously being presented in this example using the new argument inputs. Sorry for the trouble and for the delay in getting to this.
