### ISSUE TITLE
How to use mirtCAT as a module in another shiny app

### ISSUE THREAD

**Issue by peterduus** [philchalmers/mirtCAT#39]
I tested several functions of the mirtCAT package and found it's great for the survey of IRT studies.   I want to use the mirtCAT as one of the function modules in my own shiny app. However, there's no function such as  'modularize_mirtCAT()'  to extract ui and server objects.  The extract.mirtCAT() and createShinyGUI() are not for this purpose.  Is there any possible approach to embed the UI and Server into the following frameworks of the "golem" module?

```
#' mirt_cat UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd 
#'
#' @importFrom shiny NS tagList 
mod_mirt_cat_ui <- function(id){
  ns <- NS(id)
  tagList(
 
  )
}
    
#' mirt_cat Server Functions
#'
#' @noRd 
mod_mirt_cat_server <- function(id){
  moduleServer( id, function(input, output, session){
    ns <- session$ns
 
  })
}
    
## To be copied in the UI
# mod_mirt_cat_ui("mirt_cat_ui_1")
    
## To be copied in the server
# mod_mirt_cat_server("mirt_cat_ui_1")
```

**Comment by philchalmers** [comment]
Modularization of the GUI is not something I envisioned when I created the server.R file, and although it may be possible I believe your best be may be to define the CAT structure yourself using the secondary functions in the package (e.g., `updateDesign()`). That way you can control how/when the CAT information gets updated and how the GUI should progress using your code-base, which is something that the current server implementation would have difficulty knowing at the outset (to my knowledge at least).  HTH for now, and if you have some notation of how this could be possible then I'd be interested in inspecting this issue further; for now though, I'll close this issue as I don't believe it is possible.
