### ISSUE TITLE
Password example fail

### ISSUE THREAD

**Issue by MagnusNordmo** [philchalmers/mirtCAT#40]
Hi Dr. Chalmers!
I noticed that the example documentation wont run as is:

` data.frame(user = c('user1','user2'),password
= rep('1234',2))` 

However, it runs fine when `password` is capitalized:

` data.frame(user = c('user1','user2'),Password
= rep('1234',2))` 

The easiest fix is perhaps just to change the documentation? I am not familier with roxygen so i couldnt push the change on github.

- Magnus

**Comment by philchalmers** [comment]
Thanks for the report. The capitalization actually shouldn't have been a problem at all, and in the end was just one of the quirky behaviours of `data.frame` objects. The input should work now regardless of what the names of the password columns are (in the documentation no specific name was required, so it was frustrating that it could be broken when providing a meaningful one!).
