### ISSUE TITLE
Error message with "generate.mirt_object" function

### ISSUE THREAD

**Issue by YoungsoonK** [philchalmers/mirtCAT#41]
Hi Phil,

I'm keep getting the following error message -- Error in 0L:(K[i] - 1L) : NA/NaN argument -- when I ran this code:

mirt_object = generate.mirt_object(my_item_bank, itemtype =  'graded', min_category = rep(0L, length(itemtype)))

My response data ranges from 0 to 3 for each item (total 30 items) and all the item parameters entered is fine.
Could you please let me know the possible cause of this error?

Thank you!

Youngsoon

**Comment by philchalmers** [comment]
Can you provide a completely reproducible example, where `my_item_bank` and `itemtype` have been defined? Thanks for the report.

**Comment by YoungsoonK** [comment]
Hi Phil, 

Thanks for your response. I just sent my_item_bank data via your university email. 
Please let me know if you need any further information.

**Comment by philchalmers** [comment]
It seems that you were trying to create a model using a classical IRT parameterization of the graded model, which `mirt` doesn't work with (it's exclusively a slope-intercept parameterization). To fix this you need to translate the classical parameterizations into slope intercept form, which can be done via `mirt::traditional2mirt()`, like so:

```r
library(mirtCAT)

my_item_bank <- read.csv(file.choose())
inp <- my_item_bank[,2:5]

slope_int <- t(apply(inp, 1, function(x)
    mirt::traditional2mirt(x, 'graded', ncat=4)))

mirt_object = generate.mirt_object(slope_int, itemtype = 'graded', min_category = 0)
coef(mirt_object, simplify=TRUE)
```

Hope that helps.
