### ISSUE TITLE
[Bug] Incorrect MCAT Example

### ISSUE THREAD

**Issue by peterje** [philchalmers/mirtCAT#44]
The official example program presented [here](http://philchalmers.github.io/mirtCAT/html/multidim-exampleGUI.html) includes the following logic for generating a multiplication question:

```R    # multiplication
m1 <- sample(1:50, 1)
m2 <- sample(1:50, 1)
ans <- n1 + n2 + m1 * m2
questions[i] <- paste0(m1, " * ", m2, " = ?")
```

The values of n1 and n2 are arbitrary, leading to an impossible test question such as:
![image](https://user-images.githubusercontent.com/23464391/148884724-20673da0-085a-4671-8980-2821adaa17ab.png)

The correct answer is 168, but is not listed.

**Comment by philchalmers** [comment]
Thanks, should be patched on future builds.
