### ISSUE TITLE
Strange results in simulation

### ISSUE THREAD

**Issue by janstochl** [philchalmers/mirtCAT#48]
Dear Phil,
first, thanks for your amazing work on mirt and mirtCAT packages, I could not live without them. 

I have a question on strange results that I see when using EAP in MCAT simulation. In a nutshell, I see that the administration of items is finished after response to single items. This only happens when EAP is used (MAP and ML are OK.  the reason why the test is finished that the SE_theta drops to ridiculously small values (for all dimensions) after response to single item. Below is the descriptive stats on number of administered items from administrating the test to 1000 simulated individuals .

![image](https://github.com/philchalmers/mirtCAT/assets/66009884/86a7a146-0a60-416d-a97f-f6906f6ddacb)

You see that this happens basically for every EAP administration.

When I look into the single simulee theta_se_history I see that the SEs dropped to very low numbers after answering only single question, such as in the example below.

![image](https://github.com/philchalmers/mirtCAT/assets/66009884/73a5aaca-5e37-47b7-8079-793e9b2920df)

Do you have any clue why I see what I see? Your kind insights would be much appreciated, thanks for your response in advance.

Kind Regards,
Jan

**Comment by philchalmers** [comment]
Hi Jan,

Thanks for the report. I can't think of any good reason why the EAP SEs would suddenly drop to 0, so this must be a bug somewhere in the code. Could you provide a brief reprex of the issue?

**Comment by janstochl** [comment]
Thanks for response Phil, I will try to prepare it later today and send it over to you. Thanks.
Jan

Dne 12.10.2023 14:34:46, Phil Chalmers ***@***.***> napsal:

Hi Jan,

Thanks for the report. I can't think of any good reason why the EAP SEs would suddenly drop to 0, so this must be a bug somewhere in the code. Could you provide a brief reprex of the issue?

**Comment by janstochl** [comment]
Dear Phil,
please find reproducible example attached. I am sending item parameters in .RData, the actual script is in separate file. The simulation takes about 10 mins but you may reduce the number of adaptive criteria if you want to reduce the time (I wanted to demonstrate that the issue is the same regardles of criteria used).

Please let me know what you think. And of course, huge thanks for your time you spend on this.

Kind Regards,
Jan

Dne 12.10.2023 14:34:46, Phil Chalmers ***@***.***> napsal:

Hi Jan,

Thanks for the report. I can't think of any good reason why the EAP SEs would suddenly drop to 0, so this must be a bug somewhere in the code. Could you provide a brief reprex of the issue?

**Comment by philchalmers** [comment]
Hi Jan,

I don't see any attachments in the email or Github locations. Can you try uploading again?

**Comment by janstochl** [comment]
I sent via email, but it looks github is not supporting R script and RData files as attachments. I tried here and also cannot upload them. Is there any other way how I could get the files to you please? 
Sorry I am not using github that frequently.

**Comment by philchalmers** [comment]
No problem. Can you send the files directly to my gmail address?
***@***.***

Phil

**Comment by janstochl** [comment]
Phil, github is masking your email so I cannot see your email address, I basically see ***@******

**Comment by janstochl** [comment]
I think I found your gmail at York university website. Sending the files there. You will receive it from my cambridge uni address (which starts strangely with js883). Please let me know whether thi files have arrived. Thanks.

**Comment by philchalmers** [comment]
Wow, that's needlessly aggressive of Github.... Files received, thanks for keeping at it!

**Comment by janstochl** [comment]
perfect, thanks!

**Comment by philchalmers** [comment]
Hi Jan,

I see the problem here, though it's not a bug. The issue is that you have a rather high dimensional model so numerical integration is going to be a major issue. In general, I don't recommend using EAP estimators past 4 dimensions given that the integration precision must drop to accommodate the exponential growth of the grid (e.g., 6 factors and even 11 quadrature that's 11^6 = 1.7 million points to evaluate!). The package currently uses mirt's `fscores()` defaults, which admittedly are a little low (for 6 factors only 3 quadrature were used; I increased this value to 5 for the next version), however my main recommendation is to either use MAP estimates or try your luck with quasi-Monte Carlo integration to get a sparce integration grid to work with. 

At this point, I think for safety reasons I should probably throw a message to the user so that they are immediately aware of the EAP problems for high-dimensional models.

**Comment by philchalmers** [comment]
Latest dev version of mirt seems to fix this issue, however a warning is now printed in mirtCAT to deter the use of EAP estimators for high-dimensional models. Thanks for bringing this to my attention.

**Comment by janstochl** [comment]
Thanks a ton Phil for demystifying this so quickly. Good to know about limitations of EAP. Makes sense and thanks for implementing the warning.

Best wishes,
Jan



Dne 13. října 2023 16:09:28 Phil Chalmers ***@***.***> napsal:

Latest dev version of mirt seems to fix this issue, however a warning is now printed in mirtCAT to deter the use of EAP estimators for high-dimensional models. Thanks for bringing this to my attention.
