### ISSUE TITLE
No way to change "Click the action button to begin"

### ISSUE THREAD

**Issue by whiteplastic** [philchalmers/mirtCAT#5]
Is there any way to customize this line without changing the code itself? 
`return(list(h5("Click the action button to begin.")))`

**Comment by philchalmers** [comment]
Not currently, but that's easy to change. Did you want just the text to change or the option to remove the page entirely?

**Comment by whiteplastic** [comment]
I’d like to change this line of text.

**Comment by philchalmers** [comment]
The new `begin_message` input to the `shinyGUI` list now does what you need.
