### ISSUE TITLE
Error message "The new_item selected has already been administered"

### ISSUE THREAD

**Issue by UhuEngelCrash** [philchalmers/mirtCAT#51]
Dear Phil,

With mirtCAT I have found a very good, comfortable package for carrying out multidimensional CAT. When simulating the execution of multidimensional CAT with the calibration sample using findNextItem and updateDesign, the error message "The new_item selected has already been administered" is output in 4 out of 300 tests, for which there is no apparent reason. Do you perhaps have an explanation for this? I would be happy to send you the CAT script with the MIRT model.

Kind Regards,
Tom

**Comment by philchalmers** [comment]
Hi Tom,

Yes please, a reproducible script would be helpful to track this down. Thanks.
