### ISSUE TITLE
Problem with doug function 

### ISSUE THREAD

**Issue by Washingtonwlad** [philchalmers/mirtCAT#52]
I´m trying to make a mirtCAT with a item bank that i have, the problem is when I used the function dougs because the first item is correct but when I passed to the second item, it stopped, and not pass. Please help me.
[Banco de ítems 2.0.xlsx](https://github.com/philchalmers/mirtCAT/files/15341112/Banco.de.items.2.0.xlsx)

library(shiny)
library(mirtCAT)
library(mirt)
library(readxl)
library(httr)

# Cargar los datos
file_path <- "C:/Users/User/OneDrive/Desktop/Washington/Aplicaciones/7. mirtCAT/Inteligencia/Banco de ítems 2.0.xlsx"
datos_mirt <- read_excel(file_path)

# Preparar el DataFrame
df <- data.frame(
  ID_ITEM = datos_mirt$ID_ITEM,
  Question = paste0('<img src="', datos_mirt$ImageURL_Question, '" style="width:250px;"><br>', datos_mirt$Texto),
  Option.1 = datos_mirt$Option1,
  Option.2 = datos_mirt$Option2,
  Option.3 = datos_mirt$Option3,
  Option.4 = datos_mirt$Option4,
  Option.5 = datos_mirt$Option5,
  Option.6 = datos_mirt$Option6,
  Option.7 = datos_mirt$Option7,
  Option.8 = datos_mirt$Option8,
  ImageURL_Option1 = datos_mirt$ImageURL_Option1,
  ImageURL_Option2 = datos_mirt$ImageURL_Option2,
  ImageURL_Option3 = datos_mirt$ImageURL_Option3,
  ImageURL_Option4 = datos_mirt$ImageURL_Option4,
  ImageURL_Option5 = datos_mirt$ImageURL_Option5,
  ImageURL_Option6 = datos_mirt$ImageURL_Option6,
  ImageURL_Option7 = datos_mirt$ImageURL_Option7,
  ImageURL_Option8 = datos_mirt$ImageURL_Option8,
  Type = 'good_DOGS',
  stringsAsFactors = FALSE
)

# Función personalizada para manejar las opciones de tipo 'good_DOGS'
Doug <- function(inputId, df_row) {
  choiceNames <- list()
  choiceValues <- list()
  
  for (i in 1:8) {
    option <- df_row[[paste0("Option.", i)]]
    image_url <- df_row[[paste0("ImageURL_Option", i)]]
    if (!is.na(option) && option != "" && !is.na(image_url) && image_url != "") {
      choiceNames[[i]] <- tags$img(src = image_url, style = "width:100px;")
      choiceValues[[i]] <- as.character(i) # Ensure values are strings
    }
  }
  
  if (length(choiceNames) == 0 || length(choiceValues) == 0) {
    stop("Error: No se generaron opciones válidas para el ítem.")
  }
  
  list(
    h3(HTML(df_row$Question)),
    radioButtons(
      inputId = inputId,
      label = '',
      choiceNames = choiceNames,
      choiceValues = choiceValues,
      selected = ''
    )
  )
}

# Generar el objeto mirt
parameters <- data.frame(a1 = datos_mirt$a, d = datos_mirt$d)
correct_index <- as.numeric(datos_mirt$Correcta)
mirt_object <- generate.mirt_object(parameters, itemtype = "2PL", key = correct_index)

# Ejecutar mirtCAT
results <- mirtCAT(
  df = df,
  mo = mirt_object,
  customTypes = list(good_DOGS = Doug),
  criteria = 'MI',
  design = list(min_SEM = 0.32, max_items = 13),  # Ajuste de min_SEM a 0.32 según tus necesidades
  shinyGUI = list(
    forced_choice = TRUE, # Asegurarnos de que las respuestas sean forzadas
    itemtimer = "Item timer: "
  )
)

# Verificar si se está registrando la respuesta y avanzando
print("Verificar si se está registrando la respuesta y avanzando:")
print(results)
plot(results)

**Comment by philchalmers** [comment]
It seems as though the customItems input functions cannot currently be recycled as re-use of the same generating function does not progress the shiny counters. The fix in this case without modification would be to include a unique customType name for each item (like good_DOG1, good_DOG2, ...), and have the customTypes input match these (even if the function itself is recycled). I'll look into whether this is patchable on my end, but I suspect this will ultimately be a limitation based on how shiny triggers events.

**Comment by philchalmers** [comment]
Indeed, that was the problem. The following script now runs correctly on version 1.14, so please update prior to running the following:

```r
library(shiny)
library(mirtCAT)
library(mirt)
library(readxl)
library(httr)

file_path <- "~/../Downloads/Banco.de.items.2.0.xlsx"
datos_mirt <- read_excel(file_path)

df <- data.frame(
    ID_ITEM = datos_mirt$ID_ITEM,
    Question = paste0('
', datos_mirt$Texto),
    Option.1 = datos_mirt$Option1,
    Option.2 = datos_mirt$Option2,
    Option.3 = datos_mirt$Option3,
    Option.4 = datos_mirt$Option4,
    Option.5 = datos_mirt$Option5,
    Option.6 = datos_mirt$Option6,
    Option.7 = datos_mirt$Option7,
    Option.8 = datos_mirt$Option8,
    ImageURL_Option1 = datos_mirt$ImageURL_Option1,
    ImageURL_Option2 = datos_mirt$ImageURL_Option2,
    ImageURL_Option3 = datos_mirt$ImageURL_Option3,
    ImageURL_Option4 = datos_mirt$ImageURL_Option4,
    ImageURL_Option5 = datos_mirt$ImageURL_Option5,
    ImageURL_Option6 = datos_mirt$ImageURL_Option6,
    ImageURL_Option7 = datos_mirt$ImageURL_Option7,
    ImageURL_Option8 = datos_mirt$ImageURL_Option8,
    Type = 'good_DOGS',
    stringsAsFactors = FALSE
)

Doug <- function(inputId, df_row) {
    choiceNames <- list()
    choiceValues <- list()
    
    for (i in 1:8) {
        option <- df_row[[paste0("Option.", i)]]
        image_url <- df_row[[paste0("ImageURL_Option", i)]]
        if (!is.na(option) && option != "" && !is.na(image_url) && image_url != "") {
            choiceNames[[i]] <- tags$img(src = image_url, style = "width:100px;")
            choiceValues[[i]] <- as.character(i) # Ensure values are strings
        }
    }
    
    if (length(choiceNames) == 0 || length(choiceValues) == 0) {
        stop("Error: No se generaron opciones válidas para el ítem.")
    }
    
    list(
        h3(HTML(df_row$Question)),
        radioButtons(
            inputId = inputId,
            label = '',
            choiceNames = choiceNames,
            choiceValues = choiceValues,
            selected = ''
        )
    )
}


parameters <- data.frame(a1 = datos_mirt$a, d = datos_mirt$d)
correct_index <- as.numeric(datos_mirt$Correcta)
mirt_object <- generate.mirt_object(parameters, itemtype = "2PL", key = correct_index)

df$Question <- as.character(1:nrow(df))
df$Type <- paste0(df$Type, 1:nrow(df))

CT <- vector('list', nrow(df))
names(CT) <- df$Type
for(i in 1:nrow(df)) CT[[i]] <- Doug


results <- mirtCAT(
    df = df,
    mo = mirt_object,
    customTypes = CT,
    criteria = 'MI',
    design = list(min_SEM = 0.32, max_items = 13), # Ajuste de min_SEM a 0.32 según tus necesidades
)
```

I've also made a note in the helpfile so that users are aware of this quirk about `customTypes` as it's not something that is immediately obvious (even to me!). HTH for now, and thanks for bringing this to my attention.

**Comment by Washingtonwlad** [comment]
thank you very much for your help
