### ISSUE TITLE
Tempfile won't get deleted

### ISSUE THREAD

**Issue by whiteplastic** [philchalmers/mirtCAT#6]
When I set a temp_file and resume_file, this file doesn't get deleted after the CAT session is finished.

**Comment by philchalmers** [comment]
This should be fixed now. Also note that I removed the `resume_file` argument in favour of just using the `temp_file` input. If the file name is detected from a previous session then it is simply resumed at that location. If this works on your end please close the issue.

**Comment by whiteplastic** [comment]
Actually I have no idea how to install an R packet manually. I will get back to you as soon as I managed…

**Comment by philchalmers** [comment]
You can use the `devtools` package to do this, though you may need to obtain the right compilers for your system first. Instructions are here: https://github.com/philchalmers/mirt, and afterwords just use

``` r
library(devtools)
install_github('philchalmers/mirtCAT')
```

**Comment by whiteplastic** [comment]
Thanks. Installing works but I get the following error when I try to load:

```
> library(mirtCAT)
Error in get(method, envir = home) : 
  lazy-load database '/usr/local/lib/R/3.2/site-library/mirtCAT/R/mirtCAT.rdb' is corrupt
```

**Comment by philchalmers** [comment]
Strange. Try restarting R?

Phil

**Comment by whiteplastic** [comment]
Right. Issue closed.
