### ISSUE TITLE
Slider-style input

### ISSUE THREAD

**Issue by whiteplastic** [philchalmers/mirtCAT#8]
Would it be possible to enable the [input type](http://www.w3schools.com/html/html_form_input_types.asp) `range` as an option for the GUI? 
As far as I know, shiny can do that.

**Comment by philchalmers** [comment]
I'm not familiar with this (or maybe I'm just misunderstanding). What is it used for and where would it be needed?

**Comment by whiteplastic** [comment]
It is used for "slider"-style inputs, making it possible to use visual analog scales in the assessment. I'd like to use mirtCAT for psychological studies, so that would be quite a nice feature. It would allow me to rate symptom severity, etc.

**Comment by philchalmers** [comment]
Interesting idea, I'd always imagined using radio buttons for such a
purpose but I suppose sliders are also possible. I'll look into how this
can be done, thanks.

Phil

**Comment by whiteplastic** [comment]
Yes, I used radio buttons but I’m planning to use this with mobile platforms as well, so I imagined that a slider input is more comfortable for mobile devices. It would be great if this became possible. 

> Am 18.01.2016 um 16:53 schrieb Phil Chalmers notifications@github.com:
> 
> Interesting idea, I'd always imagined using radio buttons for such a
> purpose but I suppose sliders are also possible. I'll look into how this
> can be done, thanks.
> 
> Phil
>

**Comment by philchalmers** [comment]
Basic test with latest commit

``` r
library(mirtCAT)
questions <- c("Questions 1", "Questions 2", "Questions 3")
df <- data.frame(Question = questions, min = 1, max = 5, 
                 value = 3, step = 1, Type = 'slider')
res <- mirtCAT(df)
```

And some documentation added to `?mirtCAT` under the `df` input argument.

**Comment by whiteplastic** [comment]
This seems to work quite nicely in the GUI but there seems to be a problem with saving the answers:

```
df <- data.frame(Question = questions, Option = options, Type = "slider", min=0, max=100,step=1,value=50)
results <- mirtCAT_preamble(df = df, shinyGUI=guiList)
```

An error occurs here:

```
> answers <- rbind(answers,results$raw_responses)
Fehler in envRefInferField(x, what, getClass(class(x)), selfEnv) : 
  ‘raw_responses’ is not a valid field or method name for reference class “ShinyGUI”
```

**Comment by philchalmers** [comment]
This isn't quite set-up correctly, but the documentation isn't the best here so I'll clarify. 

When you use the `mirtCAT_preamble` and `createShinyGUI` functions there aren't any useful objects returned, and instead internal environments are initialized and modified as the GUI progresses (specifically, an environment called `MCE` standing for mirtCAT-environment).

To run the commands correctly and to pull out the usual person results use the following form:

``` r
df <- data.frame(...)
mirtCAT_preamble(...)
createShinyGUI(...)

results <- MCE$person
```

Otherwise, `mirtCAT_preamble` has a `final_fun` input for you decide what to do with the person object just before the session terminates (e.g., save it to disc as an .rds object, upload it to googlesheets/dropbox, etc).

**Comment by philchalmers** [comment]
Hold off playing around for the moment though, I'm in the process of converting the `$raw_responses` slot from a numeric to character vector to better handle these slider inputs. You'll see a referenced commit message when this is pushed.

**Comment by whiteplastic** [comment]
Ok, this is now working correctly.

**Comment by whiteplastic** [comment]
Is it possible to supply text anchors to the slider-style input? I'd like the extreme values of 0 and 100 to be labelled with something like "Not at all" and "As much as possible".

**Comment by philchalmers** [comment]
The new input philosophy of mirtCAT is to accept additional columns in the `df` input which match with the associated shiny inputs. So ?sliderInput shows you there is a `pre` and `post` argument, which does what you want. So just make a new `df` object with columns associated with these inputs for the respective slider items.

**Comment by whiteplastic** [comment]
This is even better. Thank you!
